name: AWS ECR Push

on:
  push:
    branches: ["main"]
    tags: ["*"]

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: "051758750426"
      AWS_REGION: "eu-central-1"
      ECR_REPO: "autobay-next-js"

    steps:
      - uses: actions/checkout@v4

      - name: Create .env
        run: |
          cat > .env << 'EOF'
          APP_ID_PROD=${{ secrets.APP_ID_PROD }}
          DEV_ID_PROD=${{ secrets.DEV_ID_PROD }}
          CERT_ID_PROD=${{ secrets.CERT_ID_PROD }}
          REDIRECT_URI_PROD=${{ secrets.REDIRECT_URI_PROD }}
          EOF

      - id: ecr-publish
        name: Build, tag, and push to ECR
        uses: bitovi/github-actions-ecr-publish@v0.1.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: ${{ env.AWS_REGION }}
          aws_ecr_repo_name: ${{ env.ECR_REPO }}
      - name: Output image refs
        run: |
          echo "Image: ${{ env.image }}"
          echo "Tag:   ${{ env.tag }}"
          echo "FQDN:  ${{env.AWS_ACCOUNT_ID}}.dkr.ecr.${{env.AWS_REGION}}.amazonaws.com/${{env.ECR_REPO}}:${{ env.tag }}"
