name: ecr-publish

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: "051758750426"
    steps:
      - uses: actions/checkout@v4

      - name: Docker info (debug)
        run: |
          docker --version
          docker buildx version || true
          test -f Dockerfile && echo "Dockerfile found at repo root"

      - id: ecr-publish
        name: Build, tag, and push to ECR
        uses: bitovi/github-actions-ecr-publish@v0.1.0
        with:
          checkout: 'false'                       
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: eu-central-1        
          aws_ecr_repo_name: autobay-next-js         
          use_sha: 'true'                            

      - name: Success
        run: echo "Docker image successfully built and pushed to ECR"
